### ISSUE TITLE
Why do you delete and recreate the env file?

### ISSUE THREAD

**Issue by kastl-ars** [LorbusChris/nextcloud-quadlet#2]
Thanks for the nice setup, Christian!

I need to dig into the details, as you set a lot of options, but this far it looks very slick and promising.

Just one question, out of curiosity:

Why to you remove the `nextcloud.env` file and then create it line by line from scratch?
https://github.com/LorbusChris/nextcloud-quadlet/blob/f8028e75b2bd4b53f07172c9e7a516419ebe91f3/playbook.yml#L96

Replacing the remove, touch and lineinfile tasks (lines 96 to 147) with just one task using a Jinja template using the same variables would do the same job?

Unless I am overlooking some cornercase, hence my question.

Kind Regards
Johannes

**Comment by LorbusChris** [comment]
I'm not super well versed with Ansible, so there's no specific reason and possibly a lot of room for improvements and simplifications. I'm happy to accept PRs :)
