### ISSUE TITLE
Setting net.ipv4.ip_unprivileged_port_start=80 from an unprivileged Quadlet file does not work

### ISSUE THREAD

**Issue by kastl-ars** [LorbusChris/nextcloud-quadlet#3]
Hi Christian,

in my tests this line did nothing, I had to create a sysctl file (as root!) with this setting.

https://github.com/LorbusChris/nextcloud-quadlet/blob/f8028e75b2bd4b53f07172c9e7a516419ebe91f3/.config/containers/systemd/nextcloud-server.container#L11

Should this work?

I might be missing something, but isn't this a security risk, if you allow an unprivileged user to open privileged ports (or redefine them as unprivileged)?

Kind Regards
Johannes

**Comment by kastl-ars** [comment]
> I might be missing something, but isn't this a security risk, if you allow an unprivileged user to open privileged ports (or redefine them as unprivileged)?

Or is this set inside a network namespace so it does not harm the host?

**Comment by LorbusChris** [comment]
> > I might be missing something, but isn't this a security risk, if you allow an unprivileged user to open privileged ports (or redefine them as unprivileged)?
> 
> Or is this set inside a network namespace so it does not harm the host?

Yes, this setting is namespaced to the container itself (see https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#sysctl) so it shouldn't be a security risk. IIRC I ran into an issue without this (on Fedora 40 Server). It could probably be dropped by configuring a different internal port for the server container, but I tried not touching the default Apache conf. I'm open to accept contributions to improve this of course!

**Comment by LorbusChris** [comment]
For the server, port 8000 is exposed to the outside by Envoy, so this setting should not be needed on the system (and it would indeed be a security issue there).

**Comment by LorbusChris** [comment]
I'm trying to better understand the issue you're running into. It does absolutely not work for you without this setting on the host? What distro are you running this on?

**Comment by kastl-ars** [comment]
OK, I did some more testing and finally understood more of the setup.

This is only set in the actual Nextcloud server container, that listens on port 80. But this port is not published, i.e. not reachable on the host. But to be able to listen on this port, the sysctl for that container's namespace might be required.

The proxy listens on port 8000, which is unprivileged, hence this can be opened without root permissions.

So, sorry, false alarm. Everything is working as expected.
