### ISSUE TITLE
Question on using UserNS for the database

### ISSUE THREAD

**Issue by kastl-ars** [LorbusChris/nextcloud-quadlet#5]
Hi Christian,

I am currently trying to understand the details of the setup. I found the `UserNS` setting, which seems to hardcode the exact user and group IDs inside the container.

For the `nextcloud-server`, `nextcloud-init` and `nextcloud-cron` containers this makes sense, as they are sharing the same set of volumes. Running the containers with different UIDs might lead to lots of funny permission errors.

Is there a reason for the `UserNS` to be used for the database container? This one is not sharing volumes with other containers as far as I can see.

Kind Regards,
Johannes

**Comment by LorbusChris** [comment]
Great question but yes, this is on purpose! Uid 999 is already hardcoded in the db image itself, and `UserNS` is just a mapping from that user inside the container to the one running the container on the outside host (see https://docs.podman.io/en/v4.4/markdown/options/userns.container.html and https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#userns). 

Quoting from the former link:
```
keep-id: creates a user namespace where the current rootless user’s UID:GID are mapped to the same values in the container. This option is not allowed for containers created by the root user.
```
Here inside the container, the db is owned by uid 999 and keep-id ensures the db files - when viewing them from the host/outside the container - is actually owned by the host user running the containers. Without this mapping, the created db would be assigned a different uid on the outside host, making them owned by a host user other than the one actually running the container and that's not what we want.

I hope this clears it up!

**Comment by kastl-ars** [comment]
Thanks for the detailed explanation, Chris! That's my "one thing I learned today"!
